#!/bin/sh

# Main command dispatcher
case "$1" in
start)
  ds4drv --hidraw --emulate-xpad &
  #ds4drv --hidraw &
  ;;
stop)
  killall ds4drv &
  ;;
*)
  echo "Usage: $0 <command>"
  echo "Commands:"
  echo "  start"
  echo "  stop"
  exit 1
  ;;
esac
