#! /bin/bash
# Sets brightness of smart lamp to brightness of bg, and sweeps through dominant colors of wallpaper 
#set -x
wallpaper_path="$HOME/.cache/wallpapers/"
output=$(swaymsg -p -t get_outputs | grep focused | awk '{print $2}')
wallpaper="$wallpaper_path$output"

########## Brightness Control:
srgb=$(convert $wallpaper -resize 1x1 txt:- | tail -1 | tr -d "srgb(%)"| awk '{print $4}' | tr "," " ")
echo $srgb
for n in $srgb; do
	((brightness+=$(printf "%.0f\n" $n)))
done
brightness=$(($brightness/3))
echo $brightness
if [ $brightness -lt 25 ]; then
	brightness="1"
elif [ $brightness -lt 45 ]; then
	brightness=13
elif [ $brightness -lt 55 ]; then
	brightness=25
elif [ $brightness -lt 65 ]; then
	brightness=35

elif [ $brightness -gt 55 ]; then
	((brightness-=45))
fi
lamp brightness $brightness
######### End Brightness

######### Color Control
#average_color=$(convert $wallpaper -resize 1x1 txt:- | tail -1 | awk '{print $3}')

average_colors=$(\
	convert $wallpaper -scale 50x50! -depth 8 +dither -colors 8 -format "%c" histogram:info: |\
	sed -n 's/^[ ]*\(.*\):.*[#]\([0-9a-fA-F]*\) .*$/\1,#\2/p' |\
	sort -r -n -k 1 -t "," |\
	awk -F "#" '{print $2}'\
)

while true; do
	for color in $average_colors; do
		lamp -e smooth -d 2000 rgb $color
		sleep 4
	done
done
########## End Color Control
