#!/usr/bin/env bash
set -xe
cache="$HOME/.cache/chromium"
ramcache="/tmp/chrome-cache-$USER"

# INIT our cache backup and remove original cache
if [ ! -L "${cache}" ] ; then
  [ -d "${cache}" ] && mv -f "$cache" "$cache"'-backup'
fi

# copy our cache backup to ram; IF EXISTS
[ -d "$cache"'-backup' ] && cp -rn "$cache"'-backup' "$ramcache"

# link our ramcache to chromium cache; IF NOT THERE
[ -L "${cache}" ] || ln -s "$ramcache" "$cache"

/usr/bin/chromium --use-gl=desktop --enable-features=VaapiVideoDecoder "$@"
