#! /bin/sh
wallpaper_path="$HOME/.cache/wallpapers/"
output=$(swaymsg -p -t get_outputs | grep focused | awk '{print $2}')
to_edit="$wallpaper_path$output"
backup="$wallpaper_path$output-backup"

echo "Changing color for $output to (input a color):"
read color

if test -f "$backup"; then
	true
else
	cp $to_edit $backup
fi

magick convert $backup -fill $color -tint 30 $to_edit
swaymsg output $output bg $to_edit fill
