#!/bin/bash
set -e
get_latest_github_release() {
  local result=$(curl -s https://api.github.com/repos/$1/$2/releases/latest)
  local jq_string=".assets[] | select(.name|match(\"${3}\$\")) | .browser_download_url"
  echo "$result" | jq -r "$jq_string"
  unset result
}
get_latest_github_release "$@"
