#!/bin/bash
shopt -s nullglob
for g in $(find /sys/kernel/iommu_groups/* -maxdepth 0 -type d | sort -V); do
  echo "IOMMU Group ${g##*/}:"
  for d in $g/devices/*; do
    echo -e "\t$(lspci -nns ${d##*/})"
  done
done

# alt:
# #!/bin/bash
#for d in /sys/kernel/iommu_groups/*/devices/*; do
#  n=${d#*/iommu_groups/*}; n=${n%%/*}
#  printf 'IOMMU Group %s ' "$n"
#  lspci -nns "${d##*/}"
#done
