#! /bin/sh
# Finds the lyrics for currently playing song
# Look at:
# https://github.com/glensc/mpd-lyrics/blob/master/lyrics.sh

song_name=$(mpc --format '%artist% %title%' | head -1)
song_name_no_whitespace=$(echo "$song_name" | tr --delete " ")

if [ "$song_name_no_whitespace" ]; then
	echo "Artist and Title: " $song_name "\n"
	clyrics $song_name | grep -v -i "Compartir en" | grep -v "Agregar a la"
else
	song_name=$(basename "$(mpc --format '%file%' | head -1)" | cut -f 1 -d '.')
	echo "File name: " $song_name "\n"
	clyrics "$song_name" | grep -v "Compartir en" | grep -v "Agregar a la"
fi
