#!/bin/sh -x

FIRST_SEAT=seat0
SECOND_SEAT=seat1

sudo loginctl attach $SECOND_SEAT /sys/devices/pci0000:00/0000:00:02.1/0000:16:00.0/usb1/1-5/1-5.2
sudo loginctl attach $SECOND_SEAT /sys/devices/pci0000:00/0000:00:08.1/0000:30:00.0/drm/card1
sudo loginctl attach $SECOND_SEAT /sys/devices/pci0000:00/0000:00:08.1/0000:30:00.1/sound/card1
sudo loginctl attach $SECOND_SEAT /sys/devices/pci0000:00/0000:00:08.1/0000:30:00.0/graphics/fb1
