#!/bin/sh
# Streams phone screen
# Look into adb tcpip
if [ "$1" = "" ]
then
	adb connect "s20fe5g:34737"
	scrcpy -b2M -m1000 -t --max-fps 30 -S --window-borderless 
	#--window-width 732 --window-height 2000
	adb disconnect
	#scrcpy -S
else
	adb connect "$1"
	scrcpy -b6M -m2000 -t --max-fps 30 -S --window-borderless
	adb disconnect
fi
