#!/bin/sh
# Streams phone screen
# Look into adb tcpip
if [ "$1" = "" ]
then
	adb connect "glxy-8:5555"
	scrcpy -b2M -m1000 -t --max-fps 15 -S --window-borderless --window-width 488 --window-height 1000 --window-height 1000
	adb disconnect
else
	adb connect "$1:5555"
	scrcpy -b2M -m1000 -t --max-fps 15 -S --window-borderless
	adb disconnect
fi
