#!/bin/bash
nvidia_gpu=$(readlink -f /dev/dri/by-path/pci-0000:10:00.0-card)
nvidia_gpu="${nvidia_gpu: -1}"
__NV_PRIME_RENDER_OFFLOAD=$nvidia_gpu \
	__VK_LAYER_NV_optimus=NVIDIA_only \
	__GLX_VENDOR_LIBRARY_NAME=nvidia \
	"$@"
