#!/bin/sh
echo 'Are you sure you wish to remove (press Return or cancel with ctl+c):'
mpc | head -n 1
read what

song_to_remove="$(mpc | head -n 1)"
playlist_pos="$(mpc -f %position% | head -n 1)"
#Delete the song
remove_line="$(mpc -f %file% | head -n 1 | sed 's/^/\/media\/Data\/mpdLibrary\//')"
ssh $MPD_HOST "rm $remove_line"
#Remove the song from playlist
mpc del $playlist_pos
#Write to log file
echo "[`date`] -> --$song_to_remove-- is now deleted..." >> ~/.mpdremove.log
