#! /bin/bash
directory="4chan_pictures"
directory_named=0
url=""

for arg in "$@"; do
	if [ "$arg" == "--help" ] || [ "$arg" == "-h" ]; then
		echo "Scrapes all media from a 4chan thread;

Usage:	
	scrape-chan target_thread_url [-d download path]

Example:
	scrape-chan 'https://boards.4chan.org/wg/thread/7565401' -d 'space-wallpapers'"
	continue
	fi
	if [ "$directory_named" == 1 ]; then
		directory=$arg
		directory_named=0
		continue
	fi
	if [ "$arg" == "-d" ]; then
		directory_named=1
		continue
	fi
	url=$arg
done
if [ "$url" != "" ]; then
	wget -P "$directory" -nd -r -l 1 -H -D i.4cdn.org -A png,gif,jpg,jpeg,webm -R '?????????????s.*' "$url"
fi
