#!/bin/bash
set -xe
NTFY_CONFIG=${NTFY_CONFIG-$HOME/.ntfy}

NTFY_SERVER=${NTFY_SERVER-$(head -n1 $NTFY_CONFIG)}
NTFY_TOPIC=${NTFY_TOPIC-$(head -n2 $NTFY_CONFIG | tail -n1)}
NTFY_TOKEN=${NTFY_TOKEN-$(tail -n1 $NTFY_CONFIG)}

TAGS=${TAGS-computer}
TITLE=${TITLE-Alert}
PRIORITY=${PRIORITY-low}
DELAY=${DELAY-}
ACTIONS=${ACTIONS-}

send_ntfy() {
	curl \
		-H "Authorization: Bearer $NTFY_TOKEN" \
		-H "Tags: $TAGS" \
		-H "Title: $TITLE" \
		-H "Priority: $PRIORITY" \
		-H "Delay: $([ DELAY -e "" ] || echo $DELAY)" \
		-H "Actions: $([ ACTIONS -e "" ] || echo $ACTIONS)" \
		-d "$@" \
		"$NTFY_SERVER/$NTFY_TOPIC"
}
send_ntfy "$@"
