#!/bin/bash
set -e
CONFIG=${NTFY_CONFIG-$HOME/.ntfy}

SERVER=${NTFY_SERVER-$(head -n1 "$CONFIG")}
TOPIC=${NTFY_TOPIC-$(head -n2 "$CONFIG" | tail -n1)}
TOKEN=${NTFY_TOKEN-$(tail -n1 "$CONFIG")}

TAGS=${TAGS-computer}
TITLE=${TITLE-Alert}
PRIORITY=${PRIORITY-3}
DELAY=${DELAY-}
ACTIONS=${ACTIONS-}

send_ntfy() {
  curl \
    -H "Authorization: Bearer $TOKEN" \
    -H "Tags: $TAGS" \
    -H "Title: $TITLE" \
    -H "X-Priority: $PRIORITY" \
    -H "Delay: $([ $DELAY -e "" ] || echo "$DELAY")" \
    -H "Actions: $([ $ACTIONS -e "" ] || echo "$ACTIONS")" \
    -d "$@" \
    "$SERVER/$TOPIC"
}
# if not sourced
(return 0 2>/dev/null) || send_ntfy "$@"
