#! /bin/bash
#set -x
if [ $1 ]; then
	pixels=$1
else
	pixels=1400000
fi
while IFS= read -r image; do
	resolution=$(convert "$image" -format "%w*%h" info:-)
	total_pixels=$(($resolution))
	if [ $total_pixels -lt $pixels ]; then
		echo "$image"
	fi
done
