#!/bin/bash
PPID=$$
set -ex

sunshine_cmd="flatpak run --filesystem=home --socket=wayland dev.lizardbyte.sunshine"
old_outputs=$(swaymsg -r -t get_outputs | jq -r '.[].name')

get_headless() {
	swaymsg -t get_outputs | jq -r '.[].name' | grep HEADLESS | tr -d '"'
}

clean_exit() {
	for output in $old_outputs; do
		swaymsg output $output enable
	done
	for output in $(get_headless); do
		swaymsg output $output unplug
	done
	pkill -TERM -P $PPID
}
trap clean_exit SIGINT

for output in $old_outputs; do
	swaymsg output $output disable
done

(get_headless | grep HEADLESS) || swaymsg create_output HEADLESS-1

for output in $(get_headless); do
	swaymsg output $output \
		mode 2412x1080@60Hz
done

sleep 2

while true; do
	$sunshine_cmd >$HOME/.config/sunshine/sunshine_flatpak.log 2>&1
	sleep 1
done

clean_exit
