#!/bin/sh

export _JAVA_AWT_WM_NONREPARENTING=1
export QT_AUTO_SCREEN_SCALE_FACTOR=1
#export QT_QPA_PLATFORM='wayland;xcb'
export QT_QPA_PLATFORM=wayland-egl
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
export QT_WAYLAND_FORCE_DPI=physical
export CLUTTER_BACKEND=wayland
export XDG_SESSION_TYPE=wayland
export ECORE_EVAS_ENGINE=wayland_egl
export ELM_ENGINE=wayland_egl
export SDL_VIDEODRIVER=wayland
export MOZ_ENABLE_WAYLAND=1
#nvidia
export NVD_BACKEND=direct
#export WLR_NO_HARDWARE_CURSORS=1

dbus-run-session sway --unsupported-gpu $@ 2>&1 | systemd-cat -t sway
