#!/bin/bash
# Not working
sudo modprobe i2c-dev

status_file=$XDG_CONFIG_HOME/i2c-8.status

if [ ! -f $status_file ] ; then
  echo DP-1 > $status_file
fi

if [ "$(cat $status_file)" = HDMI-2 ] ; then
  sudo ddcutil --bus=8 setvcp 60 12 && echo HDMI-2 $status_file
else
  sudo ddcutil --bus=8 setvcp 60 4 && echo DP-1 $status_file
fi
