#!/bin/sh


fn_send() {
	ip=192.168.178.57
	ping -c1 -W1 $ip > /dev/null && \
		printf "{\"id\":1,$1}\r\n" | nc -q 1 $ip 55443 && return
	echo "$ip not available"
}

case $1 in
	set | brightness)
		[ $2 -lt 1 ] && fn_send '"method":"set_power","params":["off", "smooth", 500]' && exit
		fn_send '"method":"set_power","params":["on","smooth",'200']'
		fn_send '"method":"set_bright","params":['$2',"smooth",'200']'
		;;
	*)
		fn_send '"method":"toggle","params":[,,]'
		;;
esac
